Less confusing deploy error message when using deploy token
Previously, the error message showed a 401 Unauthorized error when a release command or smoke check failed and a deploy token was being used. This was misleading. The deploy token did not authorized access to logs, so we were failing to load the logs. The actual error was the machine failing with a non-zero exit code.

Now, we show a helpful warning when we can't load the logs due to 401 Unauthorized and return the regular error about the machine failing with a non-zero exit code. Like this:

```
...
Smoke checks for e82d416a725248 failed: the app appears to be crashing
Check its logs: here's the last lines below, or run 'fly logs -i e82d416a725248':
Warn: not authorized to retrieve app logs (this can happen when using deploy tokens), so we can't show you what failed. Use `fly logs -i e82d416a725248` or open the monitoring dashboard to see them: https://fly.io/apps/preflight-2023-05-zl3ddoaz/monitoring?region=&instance=e82d416a725248
Error: smoke checks for e82d416a725248 failed: the app appears to be crashing
```

I added some preflight tests to help us discover deploy token regressions in the future:

```
Running Generate for Help and GraphQL client
go generate ./...
Running Build
CGO_ENABLED=0 go build -o bin/flyctl -ldflags="-X 'github.com/superfly/flyctl/internal/buildinfo.buildDate=2023-05-29T19:48:14Z' -X 'github.com/superfly/flyctl/internal/buildinfo.branchName=deploy-token-fix'" .
if [ -r .direnv/preflight ]; then . .direnv/preflight; fi; \
        go test ./test/preflight --tags=integration -v -timeout 30m --run=TestFlyDeploy_DeployToken
=== RUN   TestFlyDeploy_DeployToken_Simple
--- PASS: TestFlyDeploy_DeployToken_Simple (31.93s)
=== RUN   TestFlyDeploy_DeployToken_FailingSmokeCheck
--- PASS: TestFlyDeploy_DeployToken_FailingSmokeCheck (13.90s)
=== RUN   TestFlyDeploy_DeployToken_FailingReleaseCommand
--- PASS: TestFlyDeploy_DeployToken_FailingReleaseCommand (14.30s)
PASS
ok      github.com/superfly/flyctl/test/preflight       60.282s
```